### ISSUE TITLE
Update pytest and Docker to use `uv`

### ISSUE THREAD

**Issue by shackett** [napistu/napistu-py#79]
For pytest:

```yaml
- name: Install uv
      uses: astral-sh/setup-uv@v4
      
    - name: Install dependencies
      run: |
        uv pip install --system pytest pytest-cov
        uv pip install --system -e ".[dev,mcp]"
```

For Docker:

```bash
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
RUN uv pip install --system --no-cache -e ".[mcp,dev]"
```
